function [sensors, numSensors, attachedVehicle] = createSensors(scenario)
% createSensors Returns all sensor objects to generate detections
% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);

% Vehicle 1 radar reports clustered detections
sensors{1} = radarDataGenerator('No scanning', 'SensorIndex', 1, 'UpdateRate', 10, ...
    'MountingLocation', [0 0 0.2], 'RangeLimits', [0 50], 'FieldOfView', [60 5], ...
    'RangeResolution', 2.5, 'AzimuthResolution', 4, ...
    'Profiles', profiles, 'HasOcclusion', true, 'HasFalseAlarms', false, ...
    'TargetReportFormat', 'Clustered detections'); %, 'HasRangeRate',true);

% Vehicle 1 vision sensor reports detections
sensors{2} = visionDetectionGenerator('SensorIndex', 2, ...
    'MaxRange', 100, 'SensorLocation', [0 0], 'DetectorOutput', 'Objects only', ...
    'ActorProfiles', profiles);

% Vehicle 2 radar reports tracks
sensors{3} = radarDataGenerator('No scanning', 'SensorIndex', 3, 'UpdateRate', 10, ...
    'MountingLocation', [0 0 0.2], 'RangeLimits', [0 50], 'FieldOfView', [60 5], ...
    'RangeResolution', 2.5, 'AzimuthResolution', 4, ...
    'Profiles', profiles, 'HasOcclusion', true, 'HasFalseAlarms', false, ...
    'TargetReportFormat', 'Clustered detections'); %, 'DeletionThreshold', [3 3] , 'HasRangeRate',true);

% Vehicle 2 vision sensor reports detections
sensors{4} = visionDetectionGenerator('SensorIndex', 4, ...
    'MaxRange', 100, 'SensorLocation', [0 0], 'DetectorOutput', 'Objects only', ...
    'ActorProfiles', profiles);

% Vehicle 3 radar reports tracks
sensors{5} = radarDataGenerator('No scanning', 'SensorIndex', 5, 'UpdateRate', 10, ...
    'MountingLocation', [0 0 0.2], 'RangeLimits', [0 50], 'FieldOfView', [60 5], ...
    'RangeResolution', 2.5, 'AzimuthResolution', 4, ...
    'Profiles', profiles, 'HasOcclusion', true, 'HasFalseAlarms', false, ...
    'TargetReportFormat', 'Clustered detections'); %, 'DeletionThreshold', [3 3] , 'HasRangeRate',true);

% Vehicle 3 vision sensor reports detections
sensors{6} = visionDetectionGenerator('SensorIndex', 6, ...
    'MaxRange', 100, 'SensorLocation', [0 0], 'DetectorOutput', 'Objects only', ...
    'ActorProfiles', profiles);

attachedVehicle = [1;1;2;2;3;3];
numSensors = numel(sensors);
end